[supervisord]
nodaemon=true

[program:backend]
command=dotnet /app/backend/CosengPhotography.dll
autostart=true
autorestart=true

[program:frontend]
command=dotnet /app/frontend/CosengPhotography.Frontend.dll
autostart=true
autorestart=true
